name: ci
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: npm/action-setup@v3
              with:
                  version: 9.4.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23"
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Run Prettier
              run: npm run prettier --check .

            - name: Run Linter
              run: npm run lint

            - name: Create test env file
              run: |
                  echo "TEST_DATABASE_CLIENT=sqlite" > packages/core/.env.test
                  echo "NODE_ENV=test" >> packages/core/.env.test

            - name: Run tests
              run: cd packages/core && npm test:coverage

            - name: Build packages
              run: npm run build

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
